USE cardapio_digital;

INSERT INTO categories (name, slug) VALUES
  ('Entradas', 'entradas'),
  ('Prato Principal', 'prato-principal'),
  ('Sobremesas', 'sobremesas'),
  ('Bebidas', 'bebidas'),
  ('Carta de Vinhos', 'carta-de-vinhos')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO restaurant_branding (restaurant_name, slogan, logo_url)
SELECT 'Sabor & Mesa', 'Seu momento começa no primeiro sabor.', './assets/logo.png'
WHERE NOT EXISTS (SELECT 1 FROM restaurant_branding);

INSERT INTO products (category_id, name, description, price, image_url)
VALUES
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Bruschetta de Tomate', 'Preparado com ingredientes frescos e finalização delicada.', 18.90, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Croqueta de Costela', 'Receita artesanal da casa com temperos selecionados.', 23.30, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Bolinho de Bacalhau', 'Uma escolha especial para completar sua experiência à mesa.', 25.90, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Carpaccio da Casa', 'Preparado com ingredientes frescos e finalização delicada.', 30.30, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Dadinho de Tapioca', 'Receita artesanal da casa com temperos selecionados.', 32.90, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Camarão Crocante', 'Uma escolha especial para completar sua experiência à mesa.', 37.30, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Burrata com Pesto', 'Preparado com ingredientes frescos e finalização delicada.', 18.90, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Polenta Cremosa', 'Receita artesanal da casa com temperos selecionados.', 23.30, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Pastel de Queijo Canastra', 'Uma escolha especial para completar sua experiência à mesa.', 25.90, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Cestinha de Cogumelos', 'Preparado com ingredientes frescos e finalização delicada.', 30.30, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Tábua Sabor & Mesa', 'Receita artesanal da casa com temperos selecionados.', 32.90, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Asinha ao Mel Picante', 'Uma escolha especial para completar sua experiência à mesa.', 37.30, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Queijo Coalho Grelhado', 'Preparado com ingredientes frescos e finalização delicada.', 18.90, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Mini Arancini', 'Receita artesanal da casa com temperos selecionados.', 23.30, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Ceviche de Peixe Branco', 'Uma escolha especial para completar sua experiência à mesa.', 25.90, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Tartare de Salmão', 'Preparado com ingredientes frescos e finalização delicada.', 30.30, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Focaccia de Alecrim', 'Receita artesanal da casa com temperos selecionados.', 32.90, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Pão de Alho Artesanal', 'Uma escolha especial para completar sua experiência à mesa.', 37.30, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Linguiça Acebolada', 'Preparado com ingredientes frescos e finalização delicada.', 18.90, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Grissini com Pastas', 'Receita artesanal da casa com temperos selecionados.', 23.30, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Ostras ao Vinagrete', 'Uma escolha especial para completar sua experiência à mesa.', 25.90, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Pimentão Recheado', 'Preparado com ingredientes frescos e finalização delicada.', 30.30, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Tomate Confitado', 'Receita artesanal da casa com temperos selecionados.', 32.90, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Salada Caprese', 'Uma escolha especial para completar sua experiência à mesa.', 37.30, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Mini Quiche de Alho-Poró', 'Preparado com ingredientes frescos e finalização delicada.', 18.90, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Empada de Camarão', 'Receita artesanal da casa com temperos selecionados.', 23.30, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Chips de Batata-Doce', 'Uma escolha especial para completar sua experiência à mesa.', 25.90, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Abobrinha Marinada', 'Preparado com ingredientes frescos e finalização delicada.', 30.30, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Caponata Mediterrânea', 'Receita artesanal da casa com temperos selecionados.', 32.90, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'entradas'), 'Trio de Pastinhas', 'Uma escolha especial para completar sua experiência à mesa.', 37.30, './assets/products/entradas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Filé ao Molho de Vinho', 'Preparado com ingredientes frescos e finalização delicada.', 42.90, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Risoto de Cogumelos', 'Receita artesanal da casa com temperos selecionados.', 47.30, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Penne de Camarão', 'Uma escolha especial para completar sua experiência à mesa.', 49.90, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Peixe do Dia Grelhado', 'Preparado com ingredientes frescos e finalização delicada.', 54.30, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Parmegiana da Casa', 'Receita artesanal da casa com temperos selecionados.', 56.90, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Nhoque de Mandioquinha', 'Uma escolha especial para completar sua experiência à mesa.', 61.30, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Picanha na Brasa', 'Preparado com ingredientes frescos e finalização delicada.', 42.90, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Frango ao Limão Siciliano', 'Receita artesanal da casa com temperos selecionados.', 47.30, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Lasanha de Costela', 'Uma escolha especial para completar sua experiência à mesa.', 49.90, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Arroz de Polvo', 'Preparado com ingredientes frescos e finalização delicada.', 54.30, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Ravioli de Queijo', 'Receita artesanal da casa com temperos selecionados.', 56.90, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Bife Ancho Grelhado', 'Uma escolha especial para completar sua experiência à mesa.', 61.30, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Moqueca de Peixe', 'Preparado com ingredientes frescos e finalização delicada.', 42.90, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Pappardelle ao Ragu', 'Receita artesanal da casa com temperos selecionados.', 47.30, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Salmão com Crosta', 'Uma escolha especial para completar sua experiência à mesa.', 49.90, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Curry de Vegetais', 'Preparado com ingredientes frescos e finalização delicada.', 54.30, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Bife à Parmegiana', 'Receita artesanal da casa com temperos selecionados.', 56.90, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Risoto de Limão e Camarão', 'Uma escolha especial para completar sua experiência à mesa.', 61.30, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Escondidinho de Carne-Seca', 'Preparado com ingredientes frescos e finalização delicada.', 42.90, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Cordeiro com Ervas', 'Receita artesanal da casa com temperos selecionados.', 47.30, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Polvo na Brasa', 'Uma escolha especial para completar sua experiência à mesa.', 49.90, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Peito de Frango Recheado', 'Preparado com ingredientes frescos e finalização delicada.', 54.30, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Talharim ao Funghi', 'Receita artesanal da casa com temperos selecionados.', 56.90, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Bacalhau Mediterrâneo', 'Uma escolha especial para completar sua experiência à mesa.', 61.30, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Costela Assada', 'Preparado com ingredientes frescos e finalização delicada.', 42.90, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Nhoque ao Sugo', 'Receita artesanal da casa com temperos selecionados.', 47.30, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Arroz Cremoso de Pato', 'Uma escolha especial para completar sua experiência à mesa.', 49.90, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Torta de Palmito', 'Preparado com ingredientes frescos e finalização delicada.', 54.30, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Legumes na Brasa', 'Receita artesanal da casa com temperos selecionados.', 56.90, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'prato-principal'), 'Hambúrguer da Casa', 'Uma escolha especial para completar sua experiência à mesa.', 61.30, './assets/products/pratos-principais.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Petit Gâteau de Chocolate', 'Preparado com ingredientes frescos e finalização delicada.', 16.90, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Pudim de Leite', 'Receita artesanal da casa com temperos selecionados.', 21.30, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Tiramisu da Casa', 'Uma escolha especial para completar sua experiência à mesa.', 23.90, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Mousse de Maracujá', 'Preparado com ingredientes frescos e finalização delicada.', 28.30, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Cheesecake de Frutas Vermelhas', 'Receita artesanal da casa com temperos selecionados.', 30.90, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Banana Caramelizada', 'Uma escolha especial para completar sua experiência à mesa.', 35.30, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Brownie com Sorvete', 'Preparado com ingredientes frescos e finalização delicada.', 16.90, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Crème Brûlée', 'Receita artesanal da casa com temperos selecionados.', 21.30, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Cocada Cremosa', 'Uma escolha especial para completar sua experiência à mesa.', 23.90, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Torta de Limão', 'Preparado com ingredientes frescos e finalização delicada.', 28.30, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Panna Cotta de Baunilha', 'Receita artesanal da casa com temperos selecionados.', 30.90, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Mousse de Chocolate', 'Uma escolha especial para completar sua experiência à mesa.', 35.30, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Pavlova Tropical', 'Preparado com ingredientes frescos e finalização delicada.', 16.90, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Doce de Leite com Queijo', 'Receita artesanal da casa com temperos selecionados.', 21.30, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Sorvete Artesanal', 'Uma escolha especial para completar sua experiência à mesa.', 23.90, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Manjar de Coco', 'Preparado com ingredientes frescos e finalização delicada.', 28.30, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Bolo de Cenoura', 'Receita artesanal da casa com temperos selecionados.', 30.90, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Rabanada Brûlée', 'Uma escolha especial para completar sua experiência à mesa.', 35.30, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Mil-Folhas de Morango', 'Preparado com ingredientes frescos e finalização delicada.', 16.90, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Trufa de Café', 'Receita artesanal da casa com temperos selecionados.', 21.30, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Tartelete de Maçã', 'Uma escolha especial para completar sua experiência à mesa.', 23.90, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Affogato da Casa', 'Preparado com ingredientes frescos e finalização delicada.', 28.30, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Creme de Papaia', 'Receita artesanal da casa com temperos selecionados.', 30.90, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Churros com Doce de Leite', 'Uma escolha especial para completar sua experiência à mesa.', 35.30, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Quindim Dourado', 'Preparado com ingredientes frescos e finalização delicada.', 16.90, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Arroz-Doce Cremoso', 'Receita artesanal da casa com temperos selecionados.', 21.30, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Bolo de Amêndoas', 'Uma escolha especial para completar sua experiência à mesa.', 23.90, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Gelato de Pistache', 'Preparado com ingredientes frescos e finalização delicada.', 28.30, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Frutas da Estação', 'Receita artesanal da casa com temperos selecionados.', 30.90, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'sobremesas'), 'Trio de Docinhos', 'Uma escolha especial para completar sua experiência à mesa.', 35.30, './assets/products/sobremesas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Limonada de Hortelã', 'Preparado com ingredientes frescos e finalização delicada.', 7.90, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Suco de Uva Integral', 'Receita artesanal da casa com temperos selecionados.', 12.30, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Chá Gelado de Pêssego', 'Uma escolha especial para completar sua experiência à mesa.', 14.90, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Água com Gás', 'Preparado com ingredientes frescos e finalização delicada.', 19.30, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Água sem Gás', 'Receita artesanal da casa com temperos selecionados.', 21.90, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Refrigerante Lata', 'Uma escolha especial para completar sua experiência à mesa.', 26.30, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Soda de Maçã Verde', 'Preparado com ingredientes frescos e finalização delicada.', 7.90, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Tônica com Alecrim', 'Receita artesanal da casa com temperos selecionados.', 12.30, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Pink Lemonade', 'Uma escolha especial para completar sua experiência à mesa.', 14.90, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Mate Cítrico', 'Preparado com ingredientes frescos e finalização delicada.', 19.30, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Suco de Laranja', 'Receita artesanal da casa com temperos selecionados.', 21.90, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Suco de Abacaxi', 'Uma escolha especial para completar sua experiência à mesa.', 26.30, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Suco de Morango', 'Preparado com ingredientes frescos e finalização delicada.', 7.90, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Café Espresso', 'Receita artesanal da casa com temperos selecionados.', 12.30, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Café Coado da Casa', 'Uma escolha especial para completar sua experiência à mesa.', 14.90, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Cappuccino Cremoso', 'Preparado com ingredientes frescos e finalização delicada.', 19.30, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Chocolate Quente', 'Receita artesanal da casa com temperos selecionados.', 21.90, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Chá de Ervas', 'Uma escolha especial para completar sua experiência à mesa.', 26.30, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Kombucha de Hibisco', 'Preparado com ingredientes frescos e finalização delicada.', 7.90, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Gengibirra Artesanal', 'Receita artesanal da casa com temperos selecionados.', 12.30, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Mocktail Tropical', 'Uma escolha especial para completar sua experiência à mesa.', 14.90, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Virgin Mojito', 'Preparado com ingredientes frescos e finalização delicada.', 19.30, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Caju com Limão', 'Receita artesanal da casa com temperos selecionados.', 21.90, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Água Tônica Premium', 'Uma escolha especial para completar sua experiência à mesa.', 26.30, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Ginger Ale', 'Preparado com ingredientes frescos e finalização delicada.', 7.90, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Cold Brew', 'Receita artesanal da casa com temperos selecionados.', 12.30, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Latte de Baunilha', 'Uma escolha especial para completar sua experiência à mesa.', 14.90, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Suco Verde', 'Preparado com ingredientes frescos e finalização delicada.', 19.30, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Água de Coco', 'Receita artesanal da casa com temperos selecionados.', 21.90, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'bebidas'), 'Jarra de Limonada', 'Uma escolha especial para completar sua experiência à mesa.', 26.30, './assets/products/bebidas.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Vinho Tinto Malbec', 'Preparado com ingredientes frescos e finalização delicada.', 39.90, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Vinho Tinto Cabernet Sauvignon', 'Receita artesanal da casa com temperos selecionados.', 44.30, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Vinho Tinto Merlot', 'Uma escolha especial para completar sua experiência à mesa.', 46.90, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Vinho Tinto Pinot Noir', 'Preparado com ingredientes frescos e finalização delicada.', 51.30, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Vinho Tinto Syrah', 'Receita artesanal da casa com temperos selecionados.', 53.90, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Vinho Branco Chardonnay', 'Uma escolha especial para completar sua experiência à mesa.', 58.30, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Vinho Branco Sauvignon Blanc', 'Preparado com ingredientes frescos e finalização delicada.', 39.90, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Vinho Branco Riesling', 'Receita artesanal da casa com temperos selecionados.', 44.30, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Vinho Branco Pinot Grigio', 'Uma escolha especial para completar sua experiência à mesa.', 46.90, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Vinho Rosé Provence', 'Preparado com ingredientes frescos e finalização delicada.', 51.30, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Vinho Rosé Nacional', 'Receita artesanal da casa com temperos selecionados.', 53.90, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Espumante Brut', 'Uma escolha especial para completar sua experiência à mesa.', 58.30, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Espumante Moscatel', 'Preparado com ingredientes frescos e finalização delicada.', 39.90, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Espumante Rosé Brut', 'Receita artesanal da casa com temperos selecionados.', 44.30, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Vinho do Porto', 'Uma escolha especial para completar sua experiência à mesa.', 46.90, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Taça de Malbec', 'Preparado com ingredientes frescos e finalização delicada.', 51.30, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Taça de Chardonnay', 'Receita artesanal da casa com temperos selecionados.', 53.90, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Taça de Rosé', 'Uma escolha especial para completar sua experiência à mesa.', 58.30, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Taça de Espumante', 'Preparado com ingredientes frescos e finalização delicada.', 39.90, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Vinho Tinto Reserva', 'Receita artesanal da casa com temperos selecionados.', 44.30, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Vinho Branco Reserva', 'Uma escolha especial para completar sua experiência à mesa.', 46.90, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Vinho Verde Português', 'Preparado com ingredientes frescos e finalização delicada.', 51.30, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Lambrusco Italiano', 'Receita artesanal da casa com temperos selecionados.', 53.90, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Tempranillo Espanhol', 'Uma escolha especial para completar sua experiência à mesa.', 58.30, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Carménère Chileno', 'Preparado com ingredientes frescos e finalização delicada.', 39.90, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Tannat Uruguaio', 'Receita artesanal da casa com temperos selecionados.', 44.30, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Sangiovese Italiano', 'Uma escolha especial para completar sua experiência à mesa.', 46.90, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Pinotage Sul-Africano', 'Preparado com ingredientes frescos e finalização delicada.', 51.30, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Blend da Casa', 'Receita artesanal da casa com temperos selecionados.', 53.90, './assets/products/vinhos.jpg'),
  ((SELECT id FROM categories WHERE slug = 'carta-de-vinhos'), 'Degustação em Três Taças', 'Uma escolha especial para completar sua experiência à mesa.', 58.30, './assets/products/vinhos.jpg');

SELECT c.name AS categoria, COUNT(p.id) AS quantidade
FROM categories c
LEFT JOIN products p ON p.category_id = c.id
GROUP BY c.id, c.name
ORDER BY c.id;
